version: '3.8'
services:
  redis:
    image: redis:8-alpine
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    command: sh -c "redis-server --requirepass ${REDIS_PASSWORD}"

  bot:
    build: .
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - redis
    restart: always
